### ISSUE TITLE
CALL/SHELL doesn't then show >> prompt

### ISSUE THREAD

**Issue by greggirwin** [zsx/r3#18]
The rebol >> prompt is emitted before the call result when /shell is used.

**Comment by zsx** [comment]
Didn't see it on my system. Could you put a screen shot somewhere? Please not that when you are not redirecting the output from the command, ">>" might be buried in its output and you might not notice it. See below:

```
>> call/shell "ls"
== 23563

>> PESpin_x64.exe   lint.out    makefile-linux     makefile-msys-64  makefiles        r3-linux-armhf-g25033f8  r3-make-osxi   settings.ini
hello       makefile-32 makefile-mingw-32  makefile-osx      objs         r3-make              r3-make.exe    tests
hello.r     makefile-64 makefile-mingw-64  makefile-osxi     prep-lib-stamp   r3-make-linux        r3-view-linux  upx.exe
libffi      makefile-armv7  makefile-msys      makefile.vc       prep-view-stamp  r3-make-osx          scripts        vcbuild.bat

```

**Comment by zsx** [comment]
Oops, I though you didn't see ">>" at all (that's what the title says), but in the text, you mentioned it's emitted before result.

This is anticipated, because there are two processes contending for the console for outputing, which makes the sequence unpredictable. No synchronization is done between the processes unless you specify /wait or have I/O redirection.

**Comment by greggirwin** [comment]
Got it. Thanks. Important to note, because at first I thought the command hadn't completed correctly, since I didn't see the >>.
