### ISSUE TITLE
https crash on win32

### ISSUE THREAD

**Issue by gchiu** [zsx/r3#3]
`read https://stackoverflow.com/users/login`

will cause a windows crash whereas the Saphir version reads the html fine.

> > rebol/version
> > == 3.0.0.3.1

**Comment by zsx** [comment]
it crashes on Linux as well. I will look into it. Thanks for reporting.

**Comment by zsx** [comment]
I fixed the crash. Now it fails with a "timeout".

I checked the network communication with wireshark, and found that it was due to a "Bad Recode MAC" during the handshake.

Are you familiar with TLS? I've never worked on the TLS implementation before, so it's now a little bit beyond my knowledge.

Any help would be appriciated.

**Comment by earl** [comment]
After reporting this crash to Saphirion, @Cyphre came up with a fix as well:
https://gist.github.com/earl/87416f4ac502a66cdef7

A Saphirion build with this fix included reads https://stackoverflow.com fine.

**Comment by zsx** [comment]
Yes, this is the same fix as i did.

**Comment by cyphre** [comment]
I suspect the 'timeout' issue may be a different problem as it only happens on 64-bit linux build. Win32/64 and Linux32 works fine with the fix.

**Comment by zsx** [comment]
I agree that "timeout" could be a different problem with 64-bit linux
build. I will look into it when I get into the office.

For the casting type, I don't think that's illegal, the pointer arithmetic
is not on a void pointer, it's on a pointer pointer, which is legal. I
chose (void*_), because it's supposed to skip the first member in the
REBSER member, which is (void_) data. However, this becomes a little
pedantic, the final pointer type doesn't actually matter in this case, as
long as it's a pointer to another pointer.

Best Regards

Shixin Zeng

**Comment by cyphre** [comment]
Szeng, re void*\* casting: yup, you are right. I edited my comment short while after I posted it to remove my question, but it looks you got the unedited version by email :)

**Comment by cyphre** [comment]
Szeng, I had a quick look at the timeout on 64bit Linux ...the bug is in MD5 calculation:
;this is correct result (Win32/64,Linux32)

> > checksum/method to-binary "hello" 'md5
> > == #{5D41402ABC4B2A76B9719D911017C592}

;this is incorrect result (Linux 64)

> > checksum/method to-binary "hello" 'md5 
> > == #{F35105A127F4BE17AEC8D475B0AAAB16}

Unfortunately, I have not much time right now to debug so maybe you (or Andreas) could have a look at it?

**Comment by earl** [comment]
Cyphre somehow did find some time to debug and fix this :) It's a 64-bit issue in MD5, similar to the one we had in SHA1. Here's Cyphre's patch:

https://gist.github.com/earl/522f1ee0a8fc50a1c6d2

**Comment by zsx** [comment]
Great. I can verify the fix and pushed the change.
