### ISSUE TITLE
starting events in a server UDP 

### ISSUE THREAD

**Issue by gchiu** [zsx/r3#39]
There seems to be a problem unless I'm misreading it in that a server UDP port has to have a read on the port before it starts processing READ events.

So, something like https://gist.github.com/gchiu/0c26eddfdb89a688445e0167ef004d76 line 31 or 32 is required before incoming messages appear.

**Comment by zsx** [comment]
Yes, this is by design.

Because the port in R3 is half-duplex, you have to tell the port what you want to do. So a READ event comes as a result of the READ action, and WROTE event after a WRITE action, etc.

**Comment by hostilefork** [comment]
@zsx The name for the events was suggested to be changed to "received" and "sent".  That seems better to me than "read" and "wrote".  What do you think?

**Comment by gchiu** [comment]
What I meant is that no events are processed by the event loop until you do a read from the port, or write to the port.   You can't just wait on the port with your event handler to handle the READ event.

**Comment by zsx** [comment]
@gchiu That's correct. Because it's half-duplex, it can't handle READ and WRITE simultaneously. You need to explicitly tell WAIT the event it's going to wait for by doing a READ/WRITE. What you want is a full-duplex port, which can wait for both READ and WROTE events. Unfortunately, it's not implemented in R3. We (Atronix) also want full-duplex ports, I haven't had time to look into that yet.

**Comment by zsx** [comment]
@hostilefork The names could be better, but it's OK once you're used to it. The thing about changing it is that it breaks compatibility. If we are to change the names, all of the events need to be looked into: lookup, open etc.
