### ISSUE TITLE
Segfault in 'either not request/ask'

### ISSUE THREAD

**Issue by lpvm** [zsx/r3#4]
do %r3-gui.r3
either not request/ask "" "Do you like this?" [alert "No!"] [alert "Yes!"]

seg faults in 3.0.0.4.40 Linux libc-x64

**Comment by zsx** [comment]
Thanks for reporting.

I think this problem is fixed by this commit (
https://github.com/zsx/r3/commit/456870e5dc04cbc2f2bc08c562ad418fbda0fd20),
however, I am not ready to release another binary build. So if you want to
test it, you have to compile from source. Sorry for the inconvenience.

Best Regards

Shixin Zeng
